The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Error executing job with overrides: []
Error executing job with overrides: []
Error executing job with overrides: []
Error executing job with overrides: []
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_whu.py", line 97, in main
    accelerator = Accelerator(mixed_precision='bf16', dataloader_config=DataLoaderConfiguration(use_seedable_sampler=True), log_with='wandb', kwargs_handlers=[kwargs], step_scheduler_with_optimizer=False)
  File "train_whu.py", line 97, in main
    accelerator = Accelerator(mixed_precision='bf16', dataloader_config=DataLoaderConfiguration(use_seedable_sampler=True), log_with='wandb', kwargs_handlers=[kwargs], step_scheduler_with_optimizer=False)
  File "train_whu.py", line 97, in main
    accelerator = Accelerator(mixed_precision='bf16', dataloader_config=DataLoaderConfiguration(use_seedable_sampler=True), log_with='wandb', kwargs_handlers=[kwargs], step_scheduler_with_optimizer=False)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/accelerator.py", line 415, in __init__
    self.state = AcceleratorState(
  File "train_whu.py", line 97, in main
    accelerator = Accelerator(mixed_precision='bf16', dataloader_config=DataLoaderConfiguration(use_seedable_sampler=True), log_with='wandb', kwargs_handlers=[kwargs], step_scheduler_with_optimizer=False)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/accelerator.py", line 415, in __init__
    self.state = AcceleratorState(
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/accelerator.py", line 415, in __init__
    self.state = AcceleratorState(
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/accelerator.py", line 415, in __init__
    self.state = AcceleratorState(
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 276, in __init__
    self.set_device()
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 861, in __init__
    PartialState(cpu, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 276, in __init__
    self.set_device()
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 791, in set_device
    device_module.set_device(self.device)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 276, in __init__
    self.set_device()
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 276, in __init__
    self.set_device()
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 791, in set_device
    device_module.set_device(self.device)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 791, in set_device
    device_module.set_device(self.device)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/state.py", line 791, in set_device
    device_module.set_device(self.device)
AttributeError: module 'torch.cpu' has no attribute 'set_device'
AttributeError: module 'torch.cpu' has no attribute 'set_device'
AttributeError: module 'torch.cpu' has no attribute 'set_device'
AttributeError: module 'torch.cpu' has no attribute 'set_device'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-08-10 20:21:42,630] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3977381 closing signal SIGTERM
[2025-08-10 20:21:42,662] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3977379) of binary: /home/s0214/.conda/envs/monster/bin/python
Traceback (most recent call last):
  File "/home/s0214/.conda/envs/monster/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_whu.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-08-10_20:21:42
  host      : tesla28
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3977380)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-08-10_20:21:42
  host      : tesla28
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3977382)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-10_20:21:42
  host      : tesla28
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3977379)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
